<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\**" />
    <EmbeddedResource Remove="Resources\**" />
    <None Remove="Resources\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CALCULATOR\calcu.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CALCULATOR\Calculator.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CV\ALARCON.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CV\ALARCONCV.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CV\Form2.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CV\Form1.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CV\ESTACIO.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CV\ESTACIOCV.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CV\SEVILLANO CV PREVIEW.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CV\SEVILLANO.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CV\TAMBA.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CV\TAMBACV.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="DISPLAY PAGE\Main_Page.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="GRADING SYSTEM\Grading System Student Panel.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="LOGIN PAGE\Login_Page.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="LOGIN PAGE\Registration_Form.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="ORDERING SYSTEM\Ordering.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PAYROLL\" />
  </ItemGroup>

</Project>